name: Notify Script Execution

on:
  schedule:
    - cron: '0 0 1 * *'  # This runs on the 1st day of every month at midnight UTC
  push:
    branches:
      - main  # Runs on push to the main branch (optional)

jobs:
  notify-job:
    runs-on: ubuntu-latest  # You can choose a different environment if needed

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up environment variables
      - name: Set up environment variables
        run: |
          printf "AIRTABLE_API_KEY=%s\n" "${{ secrets.AIRTABLE_API_KEY }}" >> $GITHUB_ENV
          printf "AIRTABLE_BASE_ID=%s\n" "${{ secrets.AIRTABLE_BASE_ID }}" >> $GITHUB_ENV
          printf "AIRTABLE_TABLE_NAME=%s\n" "${{ secrets.AIRTABLE_TABLE_NAME }}" >> $GITHUB_ENV
          printf "SERVICE_ACCOUNT_KEY_JSON=%s\n" "${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}" >> $GITHUB_ENV

      # Step 5: Run the notify script
      - name: Run the notify script
        run: |
          python your_script.py  # Replace with the actual script name

